name: "colorcrunch"
logger:
  level: "INFO"

session:
  token_expiry_sec: 7200
  refresh_token_expiry_sec: 604800

socket:
  server_key: "colorcrunch-dev-key"
  port: 7350

console:
  port: 7351
  username: "admin"
  password: "adminpassword"

runtime:
  path: "/nakama/data/modules"
  js_entrypoint: "colorcrunch.js"
  env:
    - "TPX_PLATFORM_AUTH_URL="
    - "TPX_PLATFORM_EVENT_URL="
    - "TPX_PLATFORM_API_KEY="
    - "TPX_PLATFORM_TELEMETRY_EVENTS_URL="
    - "TPX_PLATFORM_IAP_VERIFY_URL=https://terapixel.games/api/v1/iap/verify"
    - "TPX_PLATFORM_IAP_ENTITLEMENTS_URL=https://terapixel.games/api/v1/iap/entitlements"
    - "TPX_PLATFORM_IAP_COINS_ADJUST_URL=https://terapixel.games/api/v1/iap/coins/adjust"
    - "TPX_PLATFORM_INTERNAL_KEY=replace-with-platform-internal-service-key"
    - "TPX_HTTP_TIMEOUT_MS=5000"
    - "COLOR_CRUNCH_LEADERBOARD_ID=colorcrunch_high_scores"
