apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "__CLOUDRUN_SERVICE__"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "20"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cloudsql-instances: "__CLOUDSQL_INSTANCES__"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: "__SERVICE_ACCOUNT_EMAIL__"
      containers:
        - image: "__IMAGE_URI__"
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: DB_ADDRESS
              valueFrom:
                secretKeyRef:
                  # Point this at the shared terapixel-platform Postgres instance.
                  name: nakama-db-address
                  key: latest
            - name: NAKAMA_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: nakama-server-key
                  key: latest
            - name: NAKAMA_SESSION_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: nakama-session-encryption-key
                  key: latest
            - name: NAKAMA_SESSION_REFRESH_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: nakama-session-refresh-encryption-key
                  key: latest
            - name: NAKAMA_RUNTIME_HTTP_KEY
              valueFrom:
                secretKeyRef:
                  name: nakama-runtime-http-key
                  key: latest
            - name: NAKAMA_CONSOLE_USERNAME
              value: "admin"
            - name: NAKAMA_CONSOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nakama-console-password
                  key: latest
            - name: TPX_PLATFORM_INTERNAL_KEY
              valueFrom:
                secretKeyRef:
                  name: tpx-platform-internal-key
                  key: latest
            - name: TPX_MAGIC_LINK_NOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: tpx-magic-link-notify-secret
                  key: latest
            - name: TPX_PLATFORM_IDENTITY_NAKAMA_AUTH_URL
              value: "__TPX_PLATFORM_IDENTITY_NAKAMA_AUTH_URL__"
            - name: TPX_PLATFORM_USERNAME_VALIDATE_URL
              value: "__TPX_PLATFORM_USERNAME_VALIDATE_URL__"
            - name: TPX_PLATFORM_TELEMETRY_EVENTS_URL
              value: "__TPX_PLATFORM_TELEMETRY_EVENTS_URL__"
            - name: TPX_GAME_ID
              value: "color_crunch"
            - name: COLOR_CRUNCH_LEADERBOARD_ID
              value: "colorcrunch_high_scores"
            - name: TPX_HTTP_TIMEOUT_MS
              value: "5000"
